# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6ce602bc3921c1999b8ebb01a606dce78785cafbcbbf358dafc6072e2b5ef042d6b606aa003ce2e2866b6e859b11a8c24fa2c6db8649d87d13507caabf4bdb7

test:
  secret_key_base: 008e750a0b61429db8dd720b61cb82c819717a8387cda08b77a01c1afa6237b27baca4b4a57f4096d3e76367e95008b96a0e25aebef83c83ccabd11056bf01b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
